export const CatalogData = [
    {
      id: 1,
      src: 'https://img.freepik.com/free-photo/digital-painting-mountain-with-colorful-tree-foreground_1340-25699.jpg?w=740&t=st=1685708239~exp=1685708839~hmac=2505c8f474096d3f69e5dbe2bcd4b91495abf950abd8b451cc852fc52c356063',
      title: 'Digital Painting of Nature',
      details:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras in finibus tortor. Sed sed lorem imperdiet, egestas risus eget, bibendum diam. In hac habitasse platea dictumst. Donec id libero nec ante maximus ultricies nec ac ex. Praesent sit amet lobortis lorem. Fusce semper eu sem id ultricies. Mauris ultricies erat eu sapien dapibus luctus. Ut ante dolor, lobortis ac augue vitae, tristique eleifend leo. Curabitur eu erat vel tortor efficitur finibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas tortor eros, eleifend id viverra a, varius eu magna. Curabitur elementum maximus lectus eget pharetra. Donec ut magna in augue posuere pharetra. Curabitur ornare leo quis lacinia congue. Mauris vitae tempus ipsum. Fusce venenatis dignissim enim a congue. Cras sed eleifend elit. Mauris accumsan, tellus vitae posuere ultrices, tortor enim accumsan nisl, eu dapibus eros leo ut lorem. Nullam egestas nulla augue, eget posuere ex aliquet a. Vestibulum ante ipsum."
    },
    {
      id: 2,
      src: 'https://img.freepik.com/free-photo/airplane_1203-3237.jpg?w=740&t=st=1685708335~exp=1685708935~hmac=5a84b4a6157300b17788ecddd9466deeacc22f03ca59bd5df621ce0f60810b87',
      title: 'Bueaty of Nature',
      details:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras in finibus tortor. Sed sed lorem imperdiet, egestas risus eget, bibendum diam. In hac habitasse platea dictumst. Donec id libero nec ante maximus ultricies nec ac ex. Praesent sit amet lobortis lorem. Fusce semper eu sem id ultricies. Mauris ultricies erat eu sapien dapibus luctus. Ut ante dolor, lobortis ac augue vitae, tristique eleifend leo. Curabitur eu erat vel tortor efficitur finibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas tortor eros, eleifend id viverra a, varius eu magna. Curabitur elementum maximus lectus eget pharetra. Donec ut magna in augue posuere pharetra. Curabitur ornare leo quis lacinia congue. Mauris vitae tempus ipsum. Fusce venenatis dignissim enim a congue. Cras sed eleifend elit. Mauris accumsan, tellus vitae posuere ultrices, tortor enim accumsan nisl, eu dapibus eros leo ut lorem. Nullam egestas nulla augue, eget posuere ex aliquet a. Vestibulum ante ipsum."
    },
    {
      id: 3,
      src: 'https://img.freepik.com/free-photo/night-sky-with-star-trail-milky-way-majesty-generative-ai_188544-12468.jpg?w=740&t=st=1685708487~exp=1685709087~hmac=7fc96e80267a0a534cb5b40b5ada2e7d64b4095b9593a66a99e7d117613c9472',
      title: 'Aurora',
      details:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras in finibus tortor. Sed sed lorem imperdiet, egestas risus eget, bibendum diam. In hac habitasse platea dictumst. Donec id libero nec ante maximus ultricies nec ac ex. Praesent sit amet lobortis lorem. Fusce semper eu sem id ultricies. Mauris ultricies erat eu sapien dapibus luctus. Ut ante dolor, lobortis ac augue vitae, tristique eleifend leo. Curabitur eu erat vel tortor efficitur finibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas tortor eros, eleifend id viverra a, varius eu magna. Curabitur elementum maximus lectus eget pharetra. Donec ut magna in augue posuere pharetra. Curabitur ornare leo quis lacinia congue. Mauris vitae tempus ipsum. Fusce venenatis dignissim enim a congue. Cras sed eleifend elit. Mauris accumsan, tellus vitae posuere ultrices, tortor enim accumsan nisl, eu dapibus eros leo ut lorem. Nullam egestas nulla augue, eget posuere ex aliquet a. Vestibulum ante ipsum."
    },
    {
      id: 4,
      src: 'https://img.freepik.com/free-photo/beautiful-seaside-landscape_23-2150423929.jpg?w=740&t=st=1685708584~exp=1685709184~hmac=dd325933f5919811e96d2d6a963acf17021f53e1c722f9c682d878ed0d7747cc',
      title: 'Beautiful Seaside Landscape',
      details:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras in finibus tortor. Sed sed lorem imperdiet, egestas risus eget, bibendum diam. In hac habitasse platea dictumst. Donec id libero nec ante maximus ultricies nec ac ex. Praesent sit amet lobortis lorem. Fusce semper eu sem id ultricies. Mauris ultricies erat eu sapien dapibus luctus. Ut ante dolor, lobortis ac augue vitae, tristique eleifend leo. Curabitur eu erat vel tortor efficitur finibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas tortor eros, eleifend id viverra a, varius eu magna. Curabitur elementum maximus lectus eget pharetra. Donec ut magna in augue posuere pharetra. Curabitur ornare leo quis lacinia congue. Mauris vitae tempus ipsum. Fusce venenatis dignissim enim a congue. Cras sed eleifend elit. Mauris accumsan, tellus vitae posuere ultrices, tortor enim accumsan nisl, eu dapibus eros leo ut lorem. Nullam egestas nulla augue, eget posuere ex aliquet a. Vestibulum ante ipsum."
    },
    {
      id: 5,
      src: 'https://img.freepik.com/free-photo/closeup-shot-little-butterfly-sitting-wildflower_181624-50698.jpg?w=740&t=st=1685709212~exp=1685709812~hmac=32083c46d638b1aaf773c609a680704c13bb0530ea4cd49c5f36ff96a535cf0e',
      title: 'Little Butterfly',
      details:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras in finibus tortor. Sed sed lorem imperdiet, egestas risus eget, bibendum diam. In hac habitasse platea dictumst. Donec id libero nec ante maximus ultricies nec ac ex. Praesent sit amet lobortis lorem. Fusce semper eu sem id ultricies. Mauris ultricies erat eu sapien dapibus luctus. Ut ante dolor, lobortis ac augue vitae, tristique eleifend leo. Curabitur eu erat vel tortor efficitur finibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas tortor eros, eleifend id viverra a, varius eu magna. Curabitur elementum maximus lectus eget pharetra. Donec ut magna in augue posuere pharetra. Curabitur ornare leo quis lacinia congue. Mauris vitae tempus ipsum. Fusce venenatis dignissim enim a congue. Cras sed eleifend elit. Mauris accumsan, tellus vitae posuere ultrices, tortor enim accumsan nisl, eu dapibus eros leo ut lorem. Nullam egestas nulla augue, eget posuere ex aliquet a. Vestibulum ante ipsum."
    },
    {
      id: 6,
      src: 'https://img.freepik.com/free-photo/wide-angle-shot-single-tree-growing-clouded-sky-during-sunset-surrounded-by-grass_181624-22807.jpg?w=740&t=st=1685709383~exp=1685709983~hmac=efcb5dd32b5a8eb76ffa40ca560cb87d488195fcf71639e9d8ed97082d15c333',
      title: 'Grass Land',
      details:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras in finibus tortor. Sed sed lorem imperdiet, egestas risus eget, bibendum diam. In hac habitasse platea dictumst. Donec id libero nec ante maximus ultricies nec ac ex. Praesent sit amet lobortis lorem. Fusce semper eu sem id ultricies. Mauris ultricies erat eu sapien dapibus luctus. Ut ante dolor, lobortis ac augue vitae, tristique eleifend leo. Curabitur eu erat vel tortor efficitur finibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas tortor eros, eleifend id viverra a, varius eu magna. Curabitur elementum maximus lectus eget pharetra. Donec ut magna in augue posuere pharetra. Curabitur ornare leo quis lacinia congue. Mauris vitae tempus ipsum. Fusce venenatis dignissim enim a congue. Cras sed eleifend elit. Mauris accumsan, tellus vitae posuere ultrices, tortor enim accumsan nisl, eu dapibus eros leo ut lorem. Nullam egestas nulla augue, eget posuere ex aliquet a. Vestibulum ante ipsum."
    },
    {
      id: 7,
      src: 'https://img.freepik.com/free-photo/whitetail-deer-standing-autumn-wood_167946-143.jpg?w=740&t=st=1685709509~exp=1685710109~hmac=bed8fad6d2d2ec826720b81549945d4e223451bbc2f8a62f6c04c96ebd58e596',
      title: 'Wild Life',
      details:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras in finibus tortor. Sed sed lorem imperdiet, egestas risus eget, bibendum diam. In hac habitasse platea dictumst. Donec id libero nec ante maximus ultricies nec ac ex. Praesent sit amet lobortis lorem. Fusce semper eu sem id ultricies. Mauris ultricies erat eu sapien dapibus luctus. Ut ante dolor, lobortis ac augue vitae, tristique eleifend leo. Curabitur eu erat vel tortor efficitur finibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas tortor eros, eleifend id viverra a, varius eu magna. Curabitur elementum maximus lectus eget pharetra. Donec ut magna in augue posuere pharetra. Curabitur ornare leo quis lacinia congue. Mauris vitae tempus ipsum. Fusce venenatis dignissim enim a congue. Cras sed eleifend elit. Mauris accumsan, tellus vitae posuere ultrices, tortor enim accumsan nisl, eu dapibus eros leo ut lorem. Nullam egestas nulla augue, eget posuere ex aliquet a. Vestibulum ante ipsum."
    },
  ]